import type { DppPassField } from '@/app/_data/sample-dpp.data';

/**
 * Dynamische Betriebsdaten (PassPer-Gruppe „Dynamic / in-use“, 21 Attribute) — Demo-Snapshot.
 */
export const VOLTSTRIDE_720_DYNAMIC_FIELDS: DppPassField[] = [
  {
    key: 'dynamic.stateOfHealth',
    label: 'Gesundheitszustand (SoH)',
    value: '82 %',
    sectionId: 'technical',
    group: 'technical-dynamic',
  },
  {
    key: 'dynamic.stateOfCharge',
    label: 'Ladezustand (SoC)',
    value: '64 %',
    sectionId: 'technical',
    group: 'technical-dynamic',
  },
  {
    key: 'dynamic.remainingCapacity',
    label: 'Restkapazität',
    value: '12,3 Ah',
    sectionId: 'technical',
    group: 'technical-dynamic',
  },
  {
    key: 'dynamic.remainingEnergy',
    label: 'Restenergie',
    value: '590 Wh',
    sectionId: 'technical',
    group: 'technical-dynamic',
  },
  {
    key: 'dynamic.fullChargeCycles',
    label: 'Volle Ladezyklen',
    value: '214',
    sectionId: 'technical',
    group: 'technical-dynamic',
  },
  {
    key: 'dynamic.equivalentFullCycles',
    label: 'Äquivalente Vollzyklen',
    value: '198',
    sectionId: 'technical',
    group: 'technical-dynamic',
  },
  {
    key: 'dynamic.energyThroughputDelivered',
    label: 'Abgegebene Energie (kumuliert)',
    value: '128 kWh',
    sectionId: 'technical',
    group: 'technical-dynamic',
  },
  {
    key: 'dynamic.energyThroughputCharged',
    label: 'Zugeführte Energie (kumuliert)',
    value: '142 kWh',
    sectionId: 'technical',
    group: 'technical-dynamic',
  },
  {
    key: 'dynamic.timeInService',
    label: 'Betriebszeit',
    value: '312 h',
    sectionId: 'technical',
    group: 'technical-dynamic',
  },
  {
    key: 'dynamic.lastUpdate',
    label: 'Letzte Aktualisierung',
    value: '2026-10-01T11:20:00Z',
    sectionId: 'technical',
    group: 'technical-dynamic',
  },
  {
    key: 'dynamic.averageTemperature',
    label: 'Durchschnittstemperatur (Betrieb)',
    value: '23 °C',
    sectionId: 'technical',
    group: 'technical-dynamic',
  },
  {
    key: 'dynamic.maxTemperatureObserved',
    label: 'Max. beobachtete Temperatur',
    value: '41 °C',
    sectionId: 'technical',
    group: 'technical-dynamic',
  },
  {
    key: 'dynamic.minTemperatureObserved',
    label: 'Min. beobachtete Temperatur',
    value: '4 °C',
    sectionId: 'technical',
    group: 'technical-dynamic',
  },
  {
    key: 'dynamic.deepDischargeEvents',
    label: 'Tiefentlade-Ereignisse',
    value: '2',
    sectionId: 'technical',
    group: 'technical-dynamic',
  },
  {
    key: 'dynamic.overloadEvents',
    label: 'Überlast-Ereignisse',
    value: '0',
    sectionId: 'technical',
    group: 'technical-dynamic',
  },
  {
    key: 'dynamic.remainingPowerCapability',
    label: 'Aktuelle Leistungsfähigkeit',
    value: '465 W',
    sectionId: 'technical',
    group: 'technical-dynamic',
  },
  {
    key: 'dynamic.internalResistancePack',
    label: 'Aktueller Innenwiderstand (Pack)',
    value: '102 mΩ',
    sectionId: 'technical',
    group: 'technical-dynamic',
  },
  {
    key: 'dynamic.roundTripEfficiencyCurrent',
    label: 'Aktuelle Round-Trip-Effizienz',
    value: '92 %',
    sectionId: 'technical',
    group: 'technical-dynamic',
  },
  {
    key: 'dynamic.capacityRetention',
    label: 'Kapazitätserhalt',
    value: '82 % der Nennkapazität',
    sectionId: 'technical',
    group: 'technical-dynamic',
  },
  {
    key: 'dynamic.powerFadeCurrent',
    label: 'Aktueller Leistungsverlust',
    value: '7 %',
    sectionId: 'technical',
    group: 'technical-dynamic',
  },
  {
    key: 'dynamic.dataSource',
    label: 'Datenquelle / Aktualisierung',
    value: 'BMS-Telemetrie · autorisierter Service (Demo)',
    sectionId: 'technical',
    group: 'technical-dynamic',
  },
];
