import type { DppPassField } from '@/app/_data/sample-dpp.data';

/**
 * Öffentliche Pflichtfelder (PassPer / Annex XIII §1, DIN DKE SPEC 99100) — Demo-Werte VoltStride 720.
 * Nicht enthalten: eingeschränkte Felder (Legitimate interest / Notified bodies), dynamische Telemetrie (21).
 */
export const VOLTSTRIDE_720_PUBLIC_FIELDS: DppPassField[] = [
  // —— Zusammenfassung (sichtbar) ——
  {
    label: 'Produkt',
    value: 'VoltStride Pack 720 · Li-ion LFP · LMT',
    sectionId: 'summary',
  },
  {
    key: 'battery.manufacturer',
    label: 'Hersteller',
    value: 'Rheinwerk Cycles GmbH',
    sectionId: 'summary',
  },
  {
    key: 'battery.weight',
    label: 'Batteriemasse',
    value: '4,1 kg',
    sectionId: 'summary',
  },
  {
    key: 'battery.rechargeable',
    label: 'Wiederaufladbar',
    value: '',
    boolean: true,
    sectionId: 'summary',
  },
  {
    key: 'battery.status',
    label: 'Lebenszyklusstatus',
    value: 'Im Einsatz (In use)',
    sectionId: 'summary',
  },
  {
    key: 'battery.warrantyPeriod',
    label: 'Garantiezeitraum',
    value: '5 Jahre / ≥ 1.000 Zyklen',
    sectionId: 'summary',
  },

  // —— Technische Stammdaten (Aufklapper, weiter unten im Pass) ——
  {
    key: 'battery.uniqueId',
    label: 'Eindeutige Batterie-ID',
    value: '7c9e6679-7425-40de-944b-e07fc1f90ae7',
    sectionId: 'technical',
    group: 'summary-identity',
  },
  {
    key: 'operator.responsibleOperatorId',
    label: 'Verantwortlicher Wirtschaftsbeteiligter',
    value: 'DE1234567890123 (EOID/EORI, Demo)',
    sectionId: 'technical',
    group: 'summary-identity',
  },
  {
    key: 'manufacturing.place',
    label: 'Herstellungsort',
    value: 'Köln, Deutschland',
    sectionId: 'technical',
    group: 'summary-identity',
  },
  {
    key: 'battery.manufacturingDate',
    label: 'Herstellungsdatum',
    value: '2025-03',
    sectionId: 'technical',
    group: 'summary-identity',
  },
  {
    key: 'battery.commissioningDate',
    label: 'Inbetriebnahme',
    value: '2025-04',
    sectionId: 'technical',
    group: 'summary-identity',
  },
  {
    label: 'Seriennummer (Pack)',
    value: 'VS-720-DE-00421',
    sectionId: 'technical',
    group: 'summary-identity',
  },
  {
    label: 'Produktfamilie',
    value:
      'Li-ion-LFP-Akku für E-Bikes (LMT), modular reparierbar, konform für den EU-Markt.',
    sectionId: 'technical',
    group: 'summary-identity',
  },

  {
    key: 'durability.expectedLifetimeYears',
    label: 'Erwartete Lebensdauer (Kalenderjahre)',
    value: '10 Jahre',
    sectionId: 'technical',
    group: 'summary-durability',
  },
  {
    key: 'durability.expectedLifetime',
    label: 'Erwartete Lebensdauer (Zyklen)',
    value: '≥ 1.000 Zyklen',
    sectionId: 'technical',
    group: 'summary-durability',
  },
  {
    key: 'durability.capacityFade',
    label: 'Kapazitätsverlust (Fade)',
    value: '≤ 20 % nach Referenztest',
    sectionId: 'technical',
    group: 'summary-durability',
  },
  {
    key: 'durability.powerFade',
    label: 'Leistungsverlust (Power fade)',
    value: '≤ 15 % nach Referenztest',
    sectionId: 'technical',
    group: 'summary-durability',
  },
  {
    key: 'durability.cycleLifeReferenceTest',
    label: 'Referenztest Zyklenlebensdauer',
    value: 'IEC 62619 · 0,5 C / 25 °C (Demo)',
    sectionId: 'technical',
    group: 'summary-durability',
  },
  {
    key: 'performance.cRate',
    label: 'C-Rate Referenztest',
    value: '0,5 C',
    sectionId: 'technical',
    group: 'summary-durability',
  },
  {
    key: 'performance.capacityThreshold',
    label: 'Kapazitätsschwelle Erschöpfung',
    value: '80 % der Nennkapazität',
    sectionId: 'technical',
    group: 'summary-durability',
  },

  {
    key: 'performance.ratedCapacity',
    label: 'Nennkapazität',
    value: '15 Ah',
    sectionId: 'technical',
    group: 'summary-performance',
  },
  {
    key: 'performance.energy',
    label: 'Nennenergie',
    value: '0,72 kWh (720 Wh)',
    sectionId: 'technical',
    group: 'summary-performance',
  },
  {
    key: 'performance.nominalVoltage',
    label: 'Nennspannung',
    value: '48 V',
    sectionId: 'technical',
    group: 'summary-performance',
  },
  {
    key: 'performance.minVoltage',
    label: 'Mindestspannung',
    value: '42 V',
    sectionId: 'technical',
    group: 'summary-performance',
  },
  {
    key: 'performance.maxVoltage',
    label: 'Höchstspannung',
    value: '54,6 V',
    sectionId: 'technical',
    group: 'summary-performance',
  },
  {
    key: 'performance.powerCapability',
    label: 'Ursprüngliche Leistungsfähigkeit',
    value: '500 W (Dauerleistung)',
    sectionId: 'technical',
    group: 'summary-performance',
  },
  {
    key: 'performance.maxPermittedPower',
    label: 'Zulässige Maximalleistung',
    value: '750 W (10 s)',
    sectionId: 'technical',
    group: 'summary-performance',
  },
  {
    key: 'performance.roundTripEfficiency',
    label: 'Anfängliche Round-Trip-Effizienz',
    value: '94 %',
    sectionId: 'technical',
    group: 'summary-performance',
  },
  {
    key: 'performance.rtEfficiencyAt50',
    label: 'Round-Trip-Effizienz bei 50 % Zyklenlebensdauer',
    value: '91 %',
    sectionId: 'technical',
    group: 'summary-performance',
  },
  {
    key: 'performance.rtEfficiencyFade',
    label: 'Effizienzverlust (Round-trip fade)',
    value: '≤ 3 % über Lebensdauer',
    sectionId: 'technical',
    group: 'summary-performance',
  },
  {
    key: 'performance.internalResistancePack',
    label: 'Anfängiger Innenwiderstand (Pack)',
    value: '85 mΩ',
    sectionId: 'technical',
    group: 'summary-performance',
  },
  {
    key: 'performance.internalResistanceCell',
    label: 'Anfängiger Innenwiderstand (Zelle)',
    value: '12 mΩ',
    sectionId: 'technical',
    group: 'summary-performance',
  },
  {
    key: 'durability.internalResistanceIncreasePack',
    label: 'Innenwiderstandsanstieg (Pack)',
    value: '≤ 30 % nach Lebensdauer',
    sectionId: 'technical',
    group: 'summary-performance',
  },
  {
    key: 'performance.temperatureRangeMin',
    label: 'Temperaturbereich (Ruhe) — untere Grenze',
    value: '−20 °C',
    sectionId: 'technical',
    group: 'summary-performance',
  },
  {
    key: 'performance.temperatureRangeMax',
    label: 'Temperaturbereich (Ruhe) — obere Grenze',
    value: '+60 °C',
    sectionId: 'technical',
    group: 'summary-performance',
  },

  {
    key: 'labelling.separateCollectionSymbol',
    label: 'Symbol getrennte Sammlung',
    value: '',
    boolean: true,
    sectionId: 'technical',
    group: 'summary-labelling',
  },
  {
    key: 'labelling.heavyMetalSymbol',
    label: 'Cd-/Pb-Symbole',
    value: 'Unter Schwellen — keine Pflichtsymbole',
    sectionId: 'technical',
    group: 'summary-labelling',
  },
  {
    key: 'labelling.carbonFootprintLabel',
    label: 'CO₂-Fußabdruck-Kennzeichnung',
    value: 'Leistungsklasse B (grafisch)',
    sectionId: 'technical',
    group: 'summary-labelling',
  },
  {
    key: 'labelling.meaningOfLabels',
    label: 'Bedeutung der Kennzeichnungen',
    value:
      'Symbole gemäß Art. 74(1)(e): Sammlung, Gefahrstoffe, CO₂-Klasse, Löschmittel — siehe Betriebsanleitung.',
    sectionId: 'technical',
    group: 'summary-labelling',
  },

  // —— Zusammensetzung ——
  {
    key: 'material.composition',
    label: 'Batteriechemie / Zusammensetzung',
    value: 'Li-ion LFP (NMC-frei) · Kathode LiFePO₄, Anode Graphit',
    sectionId: 'composition',
  },
  {
    key: 'material.criticalRawMaterials',
    label: 'Kritische Rohstoffe',
    value: '',
    sectionId: 'composition',
    listItems: [
      { name: 'Lithium', origin: 'Chile', share: '12 %' },
      { name: 'Kupfer', origin: 'Peru', share: '8 %' },
      { name: 'Graphit', origin: 'China', share: '11 %' },
    ],
  },
  {
    key: 'material.activeMaterials',
    label: 'Aktive Materialien (Kat./An./Elektrolyt)',
    value: 'LFP · Graphit · LiPF₆ in organischer Lösung (Demo)',
    sectionId: 'composition',
  },
  {
    key: 'hazardous.substances',
    label: 'Gefahrstoffe',
    value: 'Cd <0,002 % · Pb <0,01 %',
    sectionId: 'composition',
  },
  {
    key: 'hazardous.substanceImpact',
    label: 'Auswirkungen auf Umwelt / Gesundheit / Sicherheit',
    value:
      'Bei bestimmungsgemäßer Nutzung gering; bei Beschädigung thermisches Ereignis möglich — SDB beachten.',
    sectionId: 'composition',
  },

  // —— Recycelter Anteil (eigene Gruppe in Zusammensetzung) ——
  {
    key: 'recycledContent.cobalt',
    label: 'Recyceltes Kobalt (gesamt)',
    value: '0 % (LFP, ohne Co)',
    sectionId: 'composition',
    group: 'recycled-content',
  },
  {
    key: 'recycledContent.nickel',
    label: 'Recyceltes Nickel (gesamt)',
    value: '0 %',
    sectionId: 'composition',
    group: 'recycled-content',
  },
  {
    key: 'recycledContent.lithium',
    label: 'Recyceltes Lithium (gesamt)',
    value: '18 %',
    sectionId: 'composition',
    group: 'recycled-content',
  },
  {
    key: 'recycledContent.lead',
    label: 'Recyceltes Blei (gesamt)',
    value: '0 %',
    sectionId: 'composition',
    group: 'recycled-content',
  },
  {
    key: 'recycledContent.preNickel',
    label: 'Pre-Consumer Nickel',
    value: '0 %',
    sectionId: 'composition',
    group: 'recycled-content',
  },
  {
    key: 'recycledContent.preCobalt',
    label: 'Pre-Consumer Kobalt',
    value: '0 %',
    sectionId: 'composition',
    group: 'recycled-content',
  },
  {
    key: 'recycledContent.preLithium',
    label: 'Pre-Consumer Lithium',
    value: '6 %',
    sectionId: 'composition',
    group: 'recycled-content',
  },
  {
    key: 'recycledContent.preLead',
    label: 'Pre-Consumer Blei',
    value: '0 %',
    sectionId: 'composition',
    group: 'recycled-content',
  },
  {
    key: 'recycledContent.postLithium',
    label: 'Post-Consumer Lithium',
    value: '12 %',
    sectionId: 'composition',
    group: 'recycled-content',
  },
  {
    key: 'recycledContent.postNickel',
    label: 'Post-Consumer Nickel',
    value: '0 %',
    sectionId: 'composition',
    group: 'recycled-content',
  },
  {
    key: 'recycledContent.postCobalt',
    label: 'Post-Consumer Kobalt',
    value: '0 %',
    sectionId: 'composition',
    group: 'recycled-content',
  },
  {
    key: 'recycledContent.postLead',
    label: 'Post-Consumer Blei',
    value: '0 %',
    sectionId: 'composition',
    group: 'recycled-content',
  },
  {
    key: 'renewableContent.share',
    label: 'Anteil erneuerbare Inhaltsstoffe',
    value: '4 % (Verpackung & Hilfsstoffe, Demo)',
    sectionId: 'composition',
    group: 'recycled-content',
  },

  // —— CO₂ ——
  {
    key: 'carbonFootprint.total',
    label: 'CO₂-Fußabdruck',
    value: '58 kg CO₂e pro Funktionseinheit',
    sectionId: 'carbon',
  },
  {
    key: 'carbonFootprint.performanceClass',
    label: 'CO₂-Leistungsklasse',
    value: 'B',
    sectionId: 'carbon',
  },
  {
    key: 'carbonFootprint.stageRawMaterial',
    label: 'CF — Rohstoffe & Vorverarbeitung',
    value: '22 kg CO₂e',
    sectionId: 'carbon',
    group: 'carbon-detail',
  },
  {
    key: 'carbonFootprint.stageProduction',
    label: 'CF — Hauptproduktion',
    value: '28 kg CO₂e',
    sectionId: 'carbon',
    group: 'carbon-detail',
  },
  {
    key: 'carbonFootprint.stageDistribution',
    label: 'CF — Vertrieb',
    value: '4 kg CO₂e',
    sectionId: 'carbon',
    group: 'carbon-detail',
  },
  {
    key: 'carbonFootprint.stageEndOfLife',
    label: 'CF — Lebensende & Recycling',
    value: '4 kg CO₂e',
    sectionId: 'carbon',
    group: 'carbon-detail',
  },
  {
    key: 'carbonFootprint.studyUrl',
    label: 'Öffentliche CF-Studie (Link)',
    value: 'Ansehen',
    href: '#',
    sectionId: 'carbon',
    group: 'carbon-detail',
  },
  {
    key: 'carbonFootprint.studyRef',
    label: 'CF-Studie (Dokument)',
    value: 'Download',
    href: '#',
    sectionId: 'carbon',
    group: 'carbon-detail',
  },
  {
    label: 'Systemgrenze',
    value: 'Cradle-to-Gate',
    sectionId: 'carbon',
    group: 'carbon-detail',
  },
  {
    label: 'Methodik',
    value: 'ISO 14067 (Demo)',
    sectionId: 'carbon',
    group: 'carbon-detail',
  },

  // —— Reparierbarkeit ——
  {
    label: 'Reparaturkonzept',
    value: 'Modulare Zellpakete · Service-Partner EU',
    sectionId: 'repairability',
  },
  {
    label: 'Demontage',
    value: '6 Schrauben · 2×7 Zellen',
    sectionId: 'repairability',
  },
  {
    label: 'Ersatzteilverfügbarkeit',
    value: '10 Jahre (Herstellerzusage)',
    sectionId: 'repairability',
  },
  {
    key: 'labelling.extinguishingAgent',
    label: 'Geeignetes Löschmittel',
    value: 'Löschpulver (ABC), CO₂, Wassernebel — kein direkter Wasserstrahl auf offene Zellen',
    sectionId: 'repairability',
  },

  // —— Lebensende ——
  {
    label: 'Recyclingfähigkeit (Masse)',
    value: '70 % der Masse',
    sectionId: 'endOfLife',
  },
  {
    key: 'endOfLife.roleWastePrevention',
    label: 'Rolle der Nutzer — Abfallvermeidung',
    value: 'Ladegerät kompatibel halten, Tiefentladung vermeiden, mechanische Beschädigung vermeiden.',
    sectionId: 'endOfLife',
    group: 'eol-detail',
  },
  {
    key: 'endOfLife.roleSeparateCollection',
    label: 'Rolle der Nutzer — getrennte Sammlung',
    value: 'Nur über autorisierte Sammelstellen / Händler abgeben, nicht im Hausmüll.',
    sectionId: 'endOfLife',
    group: 'eol-detail',
  },
  {
    key: 'endOfLife.collectionInfo',
    label: 'Sammlung, Zweitnutzung & Behandlung',
    value: 'EU-Batterie-Rücknahme (Händler/Recycler) · Second-life nur nach Diagnose.',
    sectionId: 'endOfLife',
    group: 'eol-detail',
  },
  {
    key: 'endOfLife.safetyInstructions',
    label: 'Sicherheitshinweise Lebensende',
    value: 'Bei beschädigten Zellen: nicht öffnen, kühlen, Fachbetrieb kontaktieren.',
    sectionId: 'endOfLife',
    group: 'eol-detail',
  },

  // —— Nachweise ——
  {
    key: 'dueDiligence.report',
    label: 'Lieferketten-Due-Diligence',
    value: 'Ansehen',
    href: '#',
    sectionId: 'documents',
  },
  {
    key: 'dueDiligence.policyUrl',
    label: 'Due-Diligence-Richtlinie (Link)',
    value: 'Ansehen',
    href: '#',
    sectionId: 'documents',
  },
  {
    key: 'conformity.euDeclaration',
    label: 'EU-Konformitätserklärung',
    value: 'Download',
    href: '#',
    sectionId: 'documents',
  },
  {
    label: 'Zertifizierungen',
    value: 'Download',
    href: '#',
    sectionId: 'documents',
  },
  {
    label: 'CE-Kennzeichnung',
    value: 'Ja · ab 03/2025',
    sectionId: 'documents',
    tier: 'auditor',
  },
];
